### ISSUE TITLE
Dropdown validation

### ISSUE THREAD

**Issue by jjerome00** [jebright/flutter_form_app#2]
I noticed in this demo you validate all fields except the Dropdown.  Have you come across any solution for validating the Dropdown - such as making it a required field?

**Comment by jjerome00** [comment]
I wrote an example of a validating dropdown field. Hopefully this can help someone in the future: https://github.com/jjerome00/dropdown_formfield_demo

**Comment by jebright** [comment]
That is a great example and improvement!  I took a look at your code and incorporated the idea into my demo and gave you credit in my updated blog post.  Hope you don't mind!

**Comment by jjerome00** [comment]
No problem, I'm happy to help.  You should update your readme with a link back to your blog.
